### ISSUE TITLE
quantile sweep matrix attribute error

### ISSUE THREAD

**Issue by mjseignon** [wflynny/multiseq-py#2]
Running the quantile sweet function. I get an attribute error. Why would it not recognize "todense"? Is it a version issue?

> optimal_q, optimal_calls = multiseq.classify_by_sweep(
    tags,
    return_calls=True,
    return_proportions=False
)

This is the traceback
 ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-d44dace985ae> in <module>()
      2     tags,
      3     return_calls=True,
----> 4     return_proportions=False
      5 )

/home/seignm/.local/lib/python3.6/site-packages/multiseq/classify.py in classify_by_sweep(adata, return_calls, return_proportions)
     84     sweep_props = []
     85     for q in qs:
---> 86         sweep_calls[q] = classify_cells(adata, q=q, inplace=False)
     87         n_pos = sweep_calls[q].sum(axis=1).A1
     88         sweep_props.append([

/home/seignm/.local/lib/python3.6/site-packages/multiseq/classify.py in classify_cells(adata, q, inplace)
     12         adata.layers["raw"] = adata.X.copy()
     13 
---> 14     X = adata.X.copy().todense()
     15     X = np.log2(X + 1) - 1
     16     X[np.where(X < 0)] = 0

AttributeError: 'matrix' object has no attribute 'todense'

**Comment by wflynny** [comment]
Only sparse matrices have `todense()` methods.  Fixed in ee95876 on main.
