### ISSUE TITLE
README| Usage edits

### ISSUE THREAD

**Issue by mjseignon** [wflynny/multiseq-py#3]
1- Loading the tags, should be 
`multiseq.load_citeseq_count_matrix()`

2- Loading the gex should be:
`sc.read_10x_h5()`

3- For install: maybe also add the options below as an alternative
`!git clone git@github.com:wflynny/multiseq-py.git`
`!pip install multiseq-py/.`

This is what worked for me.

**Comment by wflynny** [comment]
1 & 2 are fixed as of 0fb423c on main.  Thanks!

I'm not going to address 3 as installing packages from within a jupyter notebook is a niche use-case.
